---
#- name: Install required packages
#  yum: name={{ item }} state=present
#  with_items:
#   - nginx
#   - git
#   - screen
#   - vim
#   - curl
#   - nodejs
#   - npm
#   - python-pip
#
#- name: Install RacksJS
#  npm: name=racksjs global=yes state=latest
#
#- name: Install Pyrax
#  pip: name=pyrax
#
- name: Nginx Daemon config
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: Nginx vHost
  template: src=vhost.conf.j2 dest=/etc/nginx/conf.d/vhost.conf
  notify: restart nginx

- name: Site index file
  template: src={{ item }}.j2 dest=/usr/share/nginx/html/{{ item  }}
  with_items:
    - index.html
    - style.css

- name: insert iptables template
  template: src=iptables.j2 dest=/etc/sysconfig/iptables
  notify: restart iptables

- name: nginx service state
  service: name=nginx state=started enabled=yes